//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGame
    {
        public int gameId { get; set; }
        public string gName { get; set; }
        public string publishedDate { get; set; }
        public string firsthHeading { get; set; }
        public string firstArticle { get; set; }
        public string author { get; set; }
        public string secondArticle { get; set; }
        public string secondHeading { get; set; }
        public string thumbImage { get; set; }
        public string thumbImg { get; set; }
    }
}
